include: "snake_utils.smk"
include: "snake_data.smk"
include: "snake_runtime.smk"
include: "snake_visualizations.smk"
include: "snake_experiments.smk"


rule all:
    """Default target: generate all figures (hierarchical structure).

    Output path: {experiment}/{model_identifier}/{data_name}:{data_group}_{status}/{plot}.png
    """
    input:
        [result_path(
            experiment=config.experiment,
            category=category,
            status=STATUS,
            plot=getattr(config, "plot", "responses"),
        ) for category in config.category]


        # expand(project_paths.figures \
        #     / '{experiment}' \
        #     / '{model_name}{model_args}_{seed}' \
        #     / '{data_name}:{data_group}_{status}' \
        #     / '{plot}.png',
        #     experiment = get_param("experiment"),
        #     model_name = MODEL_NAME,
        #     seed = SEED,
        #     model_args = args_product(DEFAULT_MODEL_ARGS.copy() | {CATEGORY[0]: '*'}),
        #     data_name = DATA_NAME,
        #     data_group = DATA_GROUP,
        #     status = STATUS,
        #     plot = get_param('plot', 'responses'),
        #     )