# Workflow parameters - running rule all
model_name: 
  - DyRCNNx8
  # - DyRCNNx4
  # - DyRCNNx2
  # - AlexNet
  # - CorNetRT
  # - CordsNet
  # - ResNet20
  # - ResNet18
  # - ResNet1202
  # - ResNet44

# seed: ["6000", "6001", "6002"] #, "6003", "6004", "6005"]
seed: ["7000", "7001", "7002"]
init_with_pretrained: False

status: [trained-best] #, trained-epoch=299]

model_args:
  tsteps: 20
  dt: 2
  tau: 5
  tff: 0
  trc: 6
  tsk: 0
  lossrt: 4
  energyloss: 0.0002 
  pattern: '1'
  # pattern: ['1', '1011']
  rctype: 'full'
  rctarget: 'output'
  skip: 'true'
  feedback: 'false'

category:
  - energyloss
  # - pattern
  - tsteps
  # - idle
  - lossrt
  # - tau
  # - trc
  # - tff
  - tsk
  - skip
  # - feedback
  - rctype
  - rctarget

data_name: imagenette
# data_name: imagenet
# data_name: tinyimagenet
# data_name: cifar100
# data_name: cifar10
# data_name: mnist

data_group: "all"
# data_group: "snakes"  # imagenet
# data_group: "imagenette"  # imagenet
# data_group: "89"  # mnist
# data_group: "mollusks"  # tinyimagenet
# data_group: "invertebrates"  # cifar100

experiment: 
  - uniformnoise
  - uniformnoiseffonly
  - contrast
  - duration
  - interval
  - response
  # - responseffonly
  # - stability

# Training parameters
loss: 
  - CrossEntropyLoss
  - EnergyLoss

